copy /y ..\..\A-Program-Counter\src ..\A-Program-Counter\src
copy /y ..\..\B-Instruction-Memory\src ..\B-Instruction-Memory\src
copy /y ..\..\C-Control-Unit\src ..\C-Control-Unit\src
copy /y ..\..\D-Registers\src ..\D-Registers\src
copy /y ..\..\E-ALU\src ..\E-ALU\src
copy /y ..\..\F-Immediates\src ..\F-Immediates\src
copy /y ..\..\G-Branch\src ..\G-Branch\src
copy /y ..\..\H-Jumps\src ..\H-Jumps\src
copy /y ..\..\I-Large-Immediate\src ..\I-Large-Immediate\src
copy /y ..\..\J-Data-Word\src ..\J-Data-Word\src
copy /y ..\..\K-Data-Aligned\src ..\K-Data-Aligned\src
copy /y ..\..\L-Data-Misaligned\src ..\L-Data-Misaligned\src
copy /y ..\..\M-Input-Output\src ..\M-Input-Output\src
copy /y ..\..\N-SOC\src ..\N-SOC\src
